version: 1
update_configs:
  package_manager: "ruby:bundler"
  directory: "/"
  update_schedule: "live"
  target_branch: "branch_that_pushes_github_too"
  default_reviewers:
    - "github_user_reviewer_12312312312312123"
  default_assignees:
    - "github_user_assignee_123123143223"
  default_labels:
    - "created_label"
  default_milestone: 1
  allowed_updates:
    # There are a lot of diff. configurations here. for now kept it simple.
    - match:
      update_type: "security"
  ignored_updates:
    - match:
      dependency_name: "express"
      # The version_requirement specifies the versions to ignore.
      # The range format is specific to the package manager
      # (e.g., ^1.0.0 for JS, or ~> 2.0 for Ruby).
      version_requirement: "4.x"
    - match:
      # Wildcards match unlimited arbitrary characters (or none)
      dependency_name: "aws*"
  # automerged_updates:
    # Leaving this out for now. This feature automerges pull requests created by Dependabot
  #version_requirement_updates:
    # Specify how Dependabot should update your package manifest (e.g. package.json, Gemfile etc), as opposed to your lockfile.
  commit_message:
    prefix: "fix"
    prefix_development: "chore"
    include_scope: true
