name: Testing github actions
on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    # Reference the major version of a release
    - uses: actions/setup-node@v1
    - uses: actions/setup-python@v1.1.1
    - uses: mrthankyou/github-action-test@v1.0
